language: rust

cache: cargo

rust:
  - stable
  - beta
  - nightly

script:
  - rustup component add rustfmt
  - cargo fmt --all -- --check

  - cargo build --verbose --all
  - cargo test --verbose --all
