[package]
name = "cmdr_derive"
version = "0.1.0"
authors = ["Mendelt Siebenga <mendelt@siebenga.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "0.4"
syn = { version = "0.15", features = ["extra-traits", "full", "fold", "parsing"] }
quote = "0.6"
