use std::io::stdout;
use std::io::stdin;
use std::io::Write;


pub fn cmd_loop(context: &mut Context) {
    loop {
        print!("{} ", context.prompt());
        stdout().flush();

        let mut input = String::new();
        stdin().read_line(&mut input).unwrap();

        context.command(parse_line(&input));
    }
}


pub enum Line<'a> {
    Empty,
    Command(&'a str, Vec<&'a str>)
}


fn parse_line<'a>(line: &'a str) -> Line<'a> {
    let mut split_line = line.trim().split(" ");

    match split_line.next() {
        None => Line::Empty,
        Some(command) => Line::Command(command, split_line.collect()),
    }
}


pub trait Context {
    fn prompt(&self) -> String {
        ">".to_string()
    }

    // Execute a single line, this function should eventually be generated by a macro
    fn command(&mut self, line: Line);

    // Execute an empty line, does nothing by default
    fn empty(&mut self) { }

    // Unknown command, shows an error by default
    fn default(&mut self, line: Line) {
        println!("Unknown command");
    }
}
